add missing button export_settings
OCA/search-engine pull request #167
Opened 2023-11-08 12:11 UTC by MrTango

2023-11-08 12:11 UTC, MrTango commented
@sebastienbeau please review

2023-12-19 11:09 UTC, bealdav approved these changes

2023-12-20 20:35 UTC, hparfr approved these changes

2024-01-09 12:34 UTC, lmignon commented on connector_search_engine/views/se_index.xml
> +                                                help="Force the export of all binding"
The help text is not the right one...

2024-01-09 12:34 UTC, lmignon requested changes
@MrTango Thank you for the contrib. A little comment...

2024-01-11 15:53 UTC, simahawk commented on connector_search_engine/views/se_index.xml
> +                                                help="Force the export of all binding"
```suggestion
                                                help="Update or initialize index settings"
```

2024-01-18 15:15 UTC, bealdav commented
Fixed by #188  cc @lmignon @simahawk

2024-01-23 12:34 UTC, lmignon commented
Superseded by #188 where the last comment has been taken into account.

2024-01-23 12:34 UTC, closed without merging