Connector typesense
OCA/search-engine pull request #168
Opened 2023-11-08 12:21 UTC by MrTango

@sebastienbeau this needs the other two (#166  #167) PR's  merged.

2024-01-09 11:31 UTC, MrTango commented
@sebastienbeau @simahawk @lmignon i would be happy to here some feedback from you.
Also please check if the readme stuff is correct, as I'm not quite sure if i understand how this in build together.

2024-01-09 13:01 UTC, lmignon requested changes
Thank you @MrTango for this contribution. I'd like to propose a first series of comments, but this seems to be going in the right direction. Great to have a new implementation for this new search engine which looks very interesting.

2024-01-09 13:01 UTC, lmignon commented on connector_typesense/models/ts_backend.py
> +# Copyright 2019 ACSONE SA/NV
By convention, this file should be renamed as `se_backend.py`

2024-01-09 13:01 UTC, lmignon commented on connector_typesense/models/ts_backend.py
> +        else:
The `else` is useless

2024-01-09 13:01 UTC, lmignon commented on connector_typesense/models/ts_index.py
> +# Copyright 2019 ACSONE SA/NV
By convention, this file should be renamed as `se_index.py`

2024-01-09 13:01 UTC, lmignon commented on connector_typesense/models/ts_backend.py
> +# Copyright 2019 ACSONE SA/NV
ACSONE does not own the copyright in this case. It should go to your company

2024-01-09 13:01 UTC, lmignon commented on connector_typesense/models/ts_index.py
> +# Copyright 2019 ACSONE SA/NV
ACSONE does not own the copyright in this case. It should go to your company

2024-01-09 13:01 UTC, lmignon commented on connector_typesense/models/ts_index.py
> +                )
Since this addon is not for "elasticsearch" but for "typesense" this code should be removed except if a config by index is also required for "typsenese".

2024-01-09 13:01 UTC, lmignon commented on connector_typesense/readme/CHANGES.rst
> +Changelog
This file should be removed

2024-01-09 13:01 UTC, lmignon commented on connector_typesense/readme/CONTRIBUTORS.rst
> +* Sébastien BEAU <sebastien.beau@akretion.com>
You are the unique contributor of this new addon. You should keep only your name here.

2024-01-09 13:01 UTC, lmignon commented on connector_typesense/readme/HISTORY.rst
> +16.0.0.1.1 (2023-10-13)
This file should be removed

2024-01-09 13:01 UTC, lmignon commented on connector_typesense/readme/INSTALL.rst
> +This addon uses the native json python package provided by python. When
This file should contain only content specific to this addon.

2024-01-09 13:01 UTC, lmignon commented on connector_typesense/readme/ROADMAP.rst
> +* Implement generic trigger for binding
This file should be removed.

2024-01-09 13:01 UTC, lmignon commented on connector_typesense/readme/TYPESENSE.rst
> +typesense
This file should be renamed as USAGE.rst to explain what typsense is.

2024-01-09 13:01 UTC, lmignon commented on connector_typesense/models/ts_backend.py
> +    )
This field seems to be not used

2024-01-09 13:01 UTC, lmignon commented on connector_typesense/models/ts_backend.py
> +    api_key = fields.Char(
B y convention you should prefix your field with `ts_`

2024-01-09 13:01 UTC, lmignon commented on connector_typesense/tools/adapter.py
> +
Commented lines should be removed

2024-01-09 13:01 UTC, lmignon commented on setup/_metapackage/setup.py
> +with open("VERSION.txt", "r") as f:
This file should not be modified.

2024-01-09 13:01 UTC, lmignon commented on setup/connector_elasticsearch/setup.py
> +    setup_requires=["setuptools-odoo"],
This file should not be modified.

2024-01-09 13:01 UTC, lmignon commented on setup/connector_search_engine/setup.py
> +    setup_requires=["setuptools-odoo"],
This file should not be modified.

2024-01-09 13:01 UTC, lmignon commented on setup/connector_search_engine_serializer_ir_export/setup.py
> +    setup_requires=["setuptools-odoo"],
This file should not be modified.

2024-01-09 13:01 UTC, lmignon commented on setup/search_engine_image_thumbnail/setup.py
> +    setup_requires=["setuptools-odoo"],
This file should not be modified.

2024-01-09 13:01 UTC, lmignon commented on setup/search_engine_serializer_pydantic/setup.py
> +    setup_requires=["setuptools-odoo"],
This file should not be modified.

2024-01-09 13:19 UTC, MrTango commented
thx @lmignon for your commends, I'll have a look at them.
One thing which is not clear to me is, how a can control the json data which is given to the connector.
I only see something like this there, no matter what product config i have:
```
{
    "id": 7,
    "name": "Office Design Software"
}
```

I would like to export more details of a product.
Any hints how to do that?
@simahawk @sebastienbeau

2024-01-09 14:43 UTC, MrTango commented on setup/search_engine_image_thumbnail/setup.py
> +    setup_requires=["setuptools-odoo"],
I'm pretty sure this came from the pre-commit command, is there something wrong in the config than?

2024-01-10 15:56 UTC, lmignon commented
> thx @lmignon for your commends, I'll have a look at them. One thing which is not clear to me is, how a can control the json data which is given to the connector. I only see something like this there, no matter what product config i have:
> 
> ```
> {
>     "id": 7,
>     "name": "Office Design Software"
> }
> ```
> 
> I would like to export more details of a product. Any hints how to do that? @simahawk @sebastienbeau

The transformation to json is the responsibility of the serializer configured on your index. You can register your specific serializer.  For example into the shoinvader project the `shopinvader_search_engine` addon defines specific serializer for products and categories based on `pydantic` schema. (https://github.com/shopinvader/odoo-shopinvader/tree/16.0/shopinvader_search_engine). You can also uses a generic serializer provided by https://github.com/OCA/search-engine/tree/16.0/connector_search_engine_serializer_ir_export and using the ir.exports rules to serialize records to json.

2024-01-13 15:34 UTC, MrTango commented
thx for the tips, i found now also that it is using ir.export model and i can define the fields for the model there.

2024-05-20 06:57 UTC, MrTango commented
Sorry for the delay, i'll continue to work on this next month.

2025-04-13 07:00 UTC, kobros-tech commented
@lmignon 
@MrTango 

How are things? If someone is busy I can help to add my upades here in the source branch for author or ceare a new active PR if the autor is busy to review.

I am really interested in connecting odoo with typesense.

2025-04-14 06:34 UTC, lmignon commented on connector_search_engine/models/se_index.py
> +        # breakpoint()
print and debug statements must be removed

2025-04-14 06:36 UTC, lmignon commented on connector_typesense/models/se_backend.py
> +    )
I would prefer to have these fields prefixed with TS

2025-04-14 06:37 UTC, lmignon requested changes

2025-04-14 06:37 UTC, lmignon commented on connector_typesense/models/se_backend.py
> +        else:
`else` is not necessary

2025-04-14 06:37 UTC, lmignon commented on connector_typesense/readme/CHANGES.rst
> +Changelog
ping

2025-04-14 06:39 UTC, lmignon commented
@kobros-tech A lot of comments are not addressed. I'll be happy to merge this new connector but the code should be finalized.  Feel free to make a new PR based on this one to complete the work.

2025-04-14 07:31 UTC, kobros-tech commented
> @kobros-tech A lot of comments are not addressed. I'll be happy to merge this new connector but the code should be finalized. Feel free to make a new PR based on this one to complete the work.

thanks, I did yesterday and I am working on it.
will improve and make professional.

2025-04-17 09:01 UTC, MrTango commented
@kobros-tech good to see your interest. I was hoping to work on it on the sprint, which was planned beginning of the year, but that didn't happen. @sebastienbeau any plans for a new date on that?
@kobros-tech let me know if you need anything or want to discuss something ;)

2025-04-17 09:05 UTC, MrTango commented on setup/search_engine_image_thumbnail/setup.py
> +    setup_requires=["setuptools-odoo"],
@lmignon did i run the pre-commit command in a wrong way or how can i run just on the module I'm working on?

2025-04-17 14:30 UTC, lmignon commented on setup/search_engine_image_thumbnail/setup.py
> +    setup_requires=["setuptools-odoo"],
@MrTango  If it's changed by pre-commit you can ignore my comments

2025-06-06 18:15 UTC, sebastienbeau commented
Replaced by : https://github.com/OCA/search-engine/pull/210

2025-06-06 18:15 UTC, closed without merging