[12.0] add settings export
OCA/search-engine pull request #27
Opened 2019-09-02 14:11 UTC by p-tombez

Port of https://github.com/akretion/connector-search-engine/pull/37

2019-09-03 14:43 UTC, simahawk requested changes
tests shall be updated

2019-09-03 14:43 UTC, simahawk commented on connector_search_engine/data/ir_cron.xml
> +        <field eval="'export_all_settings'" name="function"/>
this must be migrated to v12

2019-09-03 14:45 UTC, p-tombez commented
Not sure why the pre-commit is failing... I ran `pre-commit run --all` locally and everything is green. Does the checks on Travis are different ?

2019-11-19 10:28 UTC, simahawk commented
superseded by #38

2019-11-19 12:47 UTC, closed without merging