Add unique name by specific engine type
OCA/search-engine pull request #35
Opened 2019-10-28 13:00 UTC by simahawk

2019-10-28 17:22 UTC, lmignon approved these changes

2019-10-28 17:40 UTC, lmignon requested changes
@simahawk I changed my mind... do you thing these changes are really required? see https://github.com/shopinvader/odoo-shopinvader/pull/477#pullrequestreview-308029281

2019-10-29 10:08 UTC, lmignon approved these changes

2019-10-29 10:10 UTC, lmignon commented
After some discussions with @simahawk on shopinvader/odoo-shopinvader#477 we agree to move foward and if requried/needed improve the current implementation according to the future needs.

2019-10-29 10:10 UTC, lmignon commented
/ocabot merge patch

2019-10-29 10:11 UTC, rousseldenis approved these changes

2019-10-29 10:26 UTC, merged